---
# tasks file for common

- name: Add the user "{{ username }}" with a specific uid
  user:
    name: "{{ username }}"
    comment: John Doe
    uid: 2000
    groups: sudo
    append: yes
    shell: /bin/bash
    createhome: yes
    password: "{{ default_user_password | password_hash('sha512','A512') }}"
    state: present

- name: Creating a file with content
  copy:
    dest: "/home/{{ username }}/application.json"
    content: |
      {}
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Create directory "{{ download_directory }}"
  file:
    path: "{{ download_directory }}"
    mode: 0755
    state: directory

- name: Download file from Internet
  get_url:
    url: "{{ download_file }}"
    dest: "{{ download_directory }}"
    mode: 0755
